### ISSUE TITLE
URL links are highlighted when you hover over them. But do not open when clicked

### ISSUE THREAD

**Issue by whoizit** [tsloughter/tilda#12]
In guake, by default, they opens in my browser, if I click on them with Ctrl.

It's bug or feature? Or is there another way to open a link in tilda?

**Comment by lanoxx** [comment]
Its seems to be a bug in the URL handling code.

**Comment by lanoxx** [comment]
I just checked the code and for some reason it is required to press CTRL+Right Click in order to open the web browser. I removed that now. Feel free to pull from my repo.

**Comment by whoizit** [comment]
How to it works? Doesn't work for me.

**Comment by lanoxx** [comment]
The fix is commited in lanoxx/master

**Comment by whoizit** [comment]
This works for you? For me not.

**Comment by lanoxx** [comment]
Yes, it works for me. Previously I could use CTRL+Right Click, now I can just click on a link.

The fix is: d7d2b5ccf608e7c2f8188a5c0ce3233d1f96c7f6

Can you check under preferences "Title and Command" which web browser is configured? Maybe you need do set a different browser there. I have firefox configured but you can also try x-www-browser.

**Comment by whoizit** [comment]
I'm set xdg-open instead x-www-browser. Works now for me.

**Comment by lanoxx** [comment]
I have added a small function that checks if the configured command is valid and displays a hint if now. I also added a label pointing the user to xdg-open and x-www-browser, that should help avoid this kind of problem in the future.
